[package]
name = "dhall"
version = "0.1.0"
authors = ["NanoTech <nanotech@nanotechcorp.net>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
bytecount = "0.5.1"
lalrpop-util = "0.17.1"
nom = "5.0.0"
term-painter = "0.2.4"
